name: 💣 Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ARTIFACT_BUCKET: "micropizzeria-artifacts"

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.actor == 'paivaandeerson'
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: hashicorp/setup-terraform@v3

      - name: Empty ECR Repository
        run: |
          aws ecr list-images \
            --repository-name micropizzeria-app \
            --query 'imageIds[*]' \
            --output json | \
          jq 'if length > 0 then . else empty end' | \
          xargs -I{} aws ecr batch-delete-image \
            --repository-name micropizzeria-app \
            --image-ids {} || true

      - name: Terraform Destroy
        working-directory: ./infra
        run: |
          terraform init -input=false
          terraform state rm module.ecs || true
          terraform destroy -auto-approve -input=false \
            -var="container_image=dummy" \
            -var="image_tag=dummy" \
            -var="app_version=dummy" \
            -var="lambda_s3_key=dummy" \
            -var="artifact_bucket=dummy" \
            -var="environment=production"

      - name: Empty Artifact Bucket
        run: aws s3 rm s3://$ARTIFACT_BUCKET --recursive || true

      - name: Delete Artifact Bucket
        run: aws s3 rb s3://$ARTIFACT_BUCKET || true
