name: 💣 Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.actor == 'paivaandeerson'
    environment: production

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4️⃣ Terraform Destroy
      - name: Terraform Init & Destroy
        working-directory: ./infra
        run: |
          terraform init -input=false
          terraform destroy -auto-approve -input=false \
            -var="image_tag=dummy" \
            -var="app_version=dummy"